### ISSUE TITLE
REQUEST - Mute Audio Track

### ISSUE THREAD

**Issue by dvdenz** [bitfocus/companion-module-obs-studio#166]
Hello, it would be great if possible to be able to mute the audio tracks.
Many thanks
![image](https://user-images.githubusercontent.com/65996529/189262748-46177856-b8cf-42dd-b1d2-f42fcdd49f62.png)

**Comment by bryce-seifert** [comment]
@dvdenz You should be able to do this with either the "Set Source Mute" or "Toggle Source Mute" actions.

**Comment by dvdenz** [comment]
> @dvdenz You should be able to do this with either the "Set Source Mute" or "Toggle Source Mute" actions.

Thanks - in this case I want to mute an entire track/output (=buss) which contains multiple sources.
For example, if I have a video clip routing to tracks 1, 2, and 3. I want to mute track 2 while still having the audio routing out the other tracks, to different audio devices.

Thanks

**Comment by bryce-seifert** [comment]
Ah, sorry, I didn't realize this was "Audio Monitor" and not the default OBS "Audio Mixer".

Since this is an external plugin, there likely won't be support for it in the near future since the focus of the module is the core OBS features supported by obs-websocket, and there is currently no API to support this specific plugin. I would recommend reaching out to this plugin developer and requesting an API to control the plugin. If they implement an HTTP based API, you could use the "Generic HTTP Requests" to control it.
