### ISSUE TITLE
check connection

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-obs-studio#6]
Maybe I'm doing this to complicated but, on Windows, I try to start the OBS Studio program after a button press. Using VICREO with the. exe as parameter. This is working perfectly. But Companion isn't automatically (re) connecting with the already present OBS instance.
My goal is to start all required executables from the SD surface to ease things for my volunteers.

**Comment by JeffreyDavidsz** [comment]
This is a copy paste of Facebook

**Comment by bastiaanrodenburg** [comment]
It seems a more general issue about refreshing OBS status. Not only when started via VICREO but also when OBS is started normally Companion isn't connecting to is.

**Comment by JeffreyDavidsz** [comment]
Ok so what happens, is a OBS object is created on initializing of the module, if companion with that module is running, it doesn't make the connection. I've made a quick fix for you. A reconnect action. you could put that action after the VICREO starting up OBS (you would need to know how long it will take for OBS to start up and convert that to miliseconds).
The action has the same options as if you would update the IP settings, so it destroys the object and create a new one. Please let me know if this works for you (new build coming up).

**Comment by bastiaanrodenburg** [comment]
Thank you for the work arround, i'll try it when home. Quick question after having a look at your changes: you used reconnect and re-connect intermixed (with and without hyphen). Is that correct?

What I see with other modules is an automatic reconnect loop every 5 seconds or so. Wouldn't that be nicer?

**Comment by JeffreyDavidsz** [comment]
Yep that's a typo, a heartbeat function or so would be nice, this was a quick fix during coffee break. I'll fix the typo

**Comment by bastiaanrodenburg** [comment]
Just until now I didn't have time to work on my project. I now see that reconnect isn't working. The status in the admin GUI isn't updated. As well as the little red squares on the buttons controlling OBS.

**Comment by bastiaanrodenburg** [comment]
I realy needed to have a fix for this so I implemented my own work arround for your module. I'm using the tcp library which has an auto reconnect procedure build in. Over a tcp connection could be made to port 4444 this connection is closed immediately and your init procedure continue. It's not very beautifull because an connection is made solely as a kind of ping. But it's working! You should check to see if you would implement this in your module. For me it's working while building my own release.
[index.zip](https://github.com/bitfocus/companion-module-obs-studio/files/3837999/index.zip)

**Comment by bryce-seifert** [comment]
OBS now automatically reconnects with https://github.com/bitfocus/companion-module-obs-studio/pull/11
